In [1]:
#Standard operational package imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

from sklearn.model_selection import train_test_split
#plt.rcParams['figure.figsize']= (15, 11)
pd.set_option('display.max_columns', None)

#Random Forest Classifier, using a classifier to solve a classification problem, can also import the Random Forest Regressor to predict on continuous data 
from sklearn.ensemble import RandomForestClassifier

#This function displays the splits of the tree
from sklearn.tree import plot_tree

from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

#GridSearch
from sklearn.model_selection import GridSearchCV

import pickle

In [2]:
%load_ext autotime

time: 0 ns (started: 2025-02-04 15:36:18 +08:00)

In [3]:
sys.path.append('C:/Users/MSI Modern/Downloads/Google_Advanced_Data_Analytics_Professional/KevinVChin/6-The_Nuts_and_Bolts_of_Machine_Learning/4-Module/1-Additional_supervised_learning_techniques/Churn_Modelling.csv')

time: 0 ns (started: 2025-02-04 15:36:18 +08:00)

In [4]:
df_original= pd.read_csv('C:/Users/MSI Modern/Downloads/Google_Advanced_Data_Analytics_Professional/KevinVChin/6-The_Nuts_and_Bolts_of_Machine_Learning/4-Module/1-Additional_supervised_learning_techniques/Churn_Modelling.csv')
df_original.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

time: 62 ms (started: 2025-02-04 15:36:18 +08:00)

In [5]:
#Create new Df that drops RowNumber, CustomerId, Surname, Gender cols
churn_df= df_original.drop(['RowNumber', 'CustomerId', 'Surname', 'Gender'], axis=1)
churn_df.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,41,1,83807.86,1,0,1,112542.58,0
2,502,France,42,8,159660.80,3,1,0,113931.57,1
3,699,France,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,43,2,125510.82,1,1,1,79084.10,0

time: 16 ms (started: 2025-02-04 15:36:18 +08:00)

In [6]:
#Dummy encode categorical var
churn_df2= pd.get_dummies(churn_df, drop_first='True')
churn_df2.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True

time: 16 ms (started: 2025-02-04 15:36:18 +08:00)

In [7]:
#Split data 
y= churn_df2['Exited']

X= churn_df2.copy()
X= X.drop('Exited', axis=1 )

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, stratify= y, random_state= 42)

time: 0 ns (started: 2025-02-04 15:36:18 +08:00)

In [8]:
#%%time, Gives the runtime of the cell it's entered in

#Tune the model using cross_validation

time: 0 ns (started: 2025-02-04 15:36:18 +08:00)

In [9]:
%%time

cv_params= {'max_depth': [2, 3, 4, 5, None],
            'min_samples_leaf': [1, 2, 3],
            'min_samples_split': [2, 3, 4],
            'max_features': [2, 3, 4],
            'n_estimators': [75, 100, 125, 150]
            }

rf= RandomForestClassifier(random_state=0)

scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1'
}

rf_cv= GridSearchCV(rf, cv_params, scoring=scoring, cv=5, refit='f1')
rf_cv.fit(X_train, y_train)

CPU times: total: 19min 31s
Wall time: 19min 36s

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [2, 3, 4, 5, None],
                         'max_features': [2, 3, 4],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4],
                         'n_estimators': [75, 100, 125, 150]},
             refit='f1',
             scoring={'accuracy': 'accuracy', 'f1': 'f1',
                      'precision': 'precision', 'recall': 'recall'})

time: 19min 36s (started: 2025-02-04 15:36:18 +08:00)

In [10]:
# The more Hyperparameter searched, the better the model, but longer takes to fit
#Pickle is a tool that saves the fit model object to specify location and then quickly reads it back in, also allows the use of models that would fit somewhere else without having to train them agn

time: 0 ns (started: 2025-02-04 15:55:54 +08:00)

In [27]:
path= "C:/Users/MSI Modern/Downloads/Python Dataset/Pickel/"

time: 0 ns (started: 2025-02-04 16:06:37 +08:00)

In [29]:
#Pickle the model 
with open(path+ 'rf_cv_model_p.pickle', 'wb') as to_write:
    pickle.dump(rf_cv, to_write)
    
#'rf_cv_model_p.pickle', rf_cv_model_p= The file name, .pickle= Creates an empty pickle file
#'wb'= Give permission to write the file in binary
#pickle.dump(rf_cv, to_write), is to pass the fit model object to it, then the to_write var

time: 31 ms (started: 2025-02-04 16:06:40 +08:00)

In [31]:
#Open Pickled model 
with open(path+ 'rf_cv_model_p.pickle', 'rb') as to_read:
    rf_cv= pickle.load(to_read)

#'rb', Reading Binary

time: 47 ms (started: 2025-02-04 16:06:41 +08:00)

In [33]:
#Idendify the Hyperparameter value of the model that has the best average F1 score across all cross-validation folds

rf_cv.best_params_

{'max_depth': None,
 'max_features': 4,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 125}

time: 0 ns (started: 2025-02-04 16:06:43 +08:00)

In [35]:
#To find the average F1 score of the best model 

rf_cv.best_score_

0.580528563620339

time: 0 ns (started: 2025-02-04 16:06:44 +08:00)

In [37]:
#Concept of Pickle need to further study

time: 0 ns (started: 2025-02-04 16:06:44 +08:00)

In [41]:
def make_results(model_name, model_object):
    '''
    Accepts as arguments a model name (your choice - string) and
    a fit GridSearchCV model object.

    Returns a pandas df with the F1, recall, precision, and accuracy scores
    for the model with the best mean F1 score across all validation folds.
    '''

    # Get all the results from the CV and put them in a df
    cv_results = pd.DataFrame(model_object.cv_results_)

    # Isolate the row of the df with the max(mean f1 score)
    best_estimator_results = cv_results.iloc[cv_results['mean_test_f1'].idxmax(), :]

    # Extract accuracy, precision, recall, and f1 score from that row
    f1 = best_estimator_results.mean_test_f1
    recall = best_estimator_results.mean_test_recall
    precision = best_estimator_results.mean_test_precision
    accuracy = best_estimator_results.mean_test_accuracy

    # Create table of results
    table = pd.DataFrame({'Model': [model_name],
                          'F1': [f1],
                          'Recall': [recall],
                          'Precision': [precision],
                          'Accuracy': [accuracy]
                         }
                        )

    return table

time: 0 ns (started: 2025-02-04 16:10:34 +08:00)

In [43]:
#make_results function to generate table of all the results 

rf_cv_results= make_results('Random Forest CV', rf_cv)
rf_cv_results

              Model        F1    Recall  Precision  Accuracy
0  Random Forest CV  0.580529  0.472517   0.756289  0.861333

time: 0 ns (started: 2025-02-04 16:10:36 +08:00)

In [45]:
results= pd.read_csv('C:/Users/MSI Modern/Downloads/Python Dataset/Results.csv', index_col=0)
results

                 Model        F1    Recall  Precision  Accuracy
0  Tuned Decision Tree  0.841815  0.450935   0.742597     0.856

time: 31 ms (started: 2025-02-04 16:14:19 +08:00)

In [47]:
results= pd.concat([rf_cv_results, results])
results

                 Model        F1    Recall  Precision  Accuracy
0     Random Forest CV  0.580529  0.472517   0.756289  0.861333
0  Tuned Decision Tree  0.841815  0.450935   0.742597  0.856000

time: 16 ms (started: 2025-02-04 16:14:58 +08:00)

In [49]:
#Create seperate validation data 
X_tr, X_val, y_tr, y_val= train_test_split(X_train, y_train, test_size= 0.2,
                                          stratify= y_train, random_state=10)

time: 0 ns (started: 2025-02-04 16:18:54 +08:00)

In [53]:
split_index= [0 if x in X_val.index else -1 for x in X_train.index]

#To be figure out

time: 15 ms (started: 2025-02-04 16:25:12 +08:00)

In [61]:
from sklearn.model_selection import PredefinedSplit

#Provide train/ test indices to split data into training 
#And test sets using a predefined scheme

time: 16 ms (started: 2025-02-04 16:27:07 +08:00)

In [63]:
cv_params= {'max_depth': [2, 3, 4, 5, None],
            'min_samples_leaf': [1, 2, 3],
            'min_samples_split': [2, 3, 4],
            'max_features': [2, 3, 4],
            'n_estimators': [75, 100, 125, 150]
            }

rf= RandomForestClassifier(random_state=0)

scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1'
}

custom_split= PredefinedSplit(split_index)

rf_val= GridSearchCV(rf, cv_params, scoring=scoring, cv= custom_split, refit= 'f1')

time: 0 ns (started: 2025-02-04 16:30:13 +08:00)

In [65]:
%%time

rf_val.fit(X_train, y_train)

CPU times: total: 4min 16s
Wall time: 4min 17s

GridSearchCV(cv=PredefinedSplit(test_fold=array([-1,  0, ..., -1, -1])),
             estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [2, 3, 4, 5, None],
                         'max_features': [2, 3, 4],
                         'min_samples_leaf': [1, 2, 3],
                         'min_samples_split': [2, 3, 4],
                         'n_estimators': [75, 100, 125, 150]},
             refit='f1',
             scoring={'accuracy': 'accuracy', 'f1': 'f1',
                      'precision': 'precision', 'recall': 'recall'})

time: 4min 17s (started: 2025-02-04 16:30:39 +08:00)

In [67]:
# Cell has already been run and saved

# Pickle the model
with open(path+'rf_val_model.pickle', 'wb') as to_write:
   pickle.dump(rf_val, to_write)

time: 31 ms (started: 2025-02-04 16:37:30 +08:00)

In [69]:
# Open pickled model
with open(path+ 'rf_val_model.pickle', 'rb') as to_read:
    rf_val = pickle.load(to_read)

time: 31 ms (started: 2025-02-04 16:37:30 +08:00)

In [71]:
rf_val.best_params_

{'max_depth': None,
 'max_features': 4,
 'min_samples_leaf': 1,
 'min_samples_split': 3,
 'n_estimators': 150}

time: 16 ms (started: 2025-02-04 16:37:59 +08:00)

In [73]:
rf_val_results= make_results('Random Forest Validated', rf_val)
results= pd.concat([rf_val_results, results])
results.sort_values(by=['F1'], ascending= False)

                     Model        F1    Recall  Precision  Accuracy
0      Tuned Decision Tree  0.841815  0.450935   0.742597  0.856000
0         Random Forest CV  0.580529  0.472517   0.756289  0.861333
0  Random Forest Validated  0.575510  0.460784   0.766304  0.861333

time: 16 ms (started: 2025-02-04 16:40:05 +08:00)

In [ ]:
#Required to refer Annotated guide

In [ ]:
#Boosting 
#Technique that builds an ensemble of weak learners sequentially, with each consecutive learner trying to correct the errors of the one that preceded it 
#Random Forest= Build model parallel 
#Boosting= Build model sequentially, not limited to the tree-based learner

#Adaptive Boosting(AdaBoosting)
#Boosting methodology where each consecutive base learner assigns greater weight to the observations incorrectly predicted by the preceding learner

#Gradient Boosting
#Each base learned in the sequence is built to predict the residual errors of the model that preceded it